# Generated by Django 5.2.16 on 2026-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_First_Name', models.CharField(max_length=150)),
                ('student_Last_Name', models.CharField(max_length=150)),
                ('student_Email_Id', models.EmailField(max_length=254)),
                ('course_Name', models.CharField(max_length=150)),
                ('student_Age', models.IntegerField()),
            ],
        ),
    ]
