# Generated by Django 5.2.16 on 2026-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_Duration',
            field=models.CharField(default='3 Months', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course_Fees',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=8),
        ),
    ]
