# Generated by Django 5.2.16 on 2026-09-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student_course_duration_student_course_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Enrolled', 'Enrolled')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_Fees',
            field=models.IntegerField(),
        ),
    ]
